### ISSUE TITLE
Add support for new QP solver

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava-optimization#104]
Objective of issue: Adding process interface for new QP solver along with floating point models

**Lava version:**
- [x] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [ ] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- Currently 1 QP solver exists in the repo. This issue is about adding a new QP solver which also acts as the QP solver that can run on hardware (for INRC members and people who have access). Eventified floating point version of the solver is available publicly

**Comment by GaboFGuerra** [comment]
@ashishrao7 would it be possible for you to adhere to the generic solver when addressing this issue? Or do we need an extra issue for that?

**Comment by ashishrao7** [comment]
I will create a new issue for that. This issue mentioned here has already been dealt with in a previous PR
