### ISSUE TITLE
Integer overflow bug in OptimizationSolver

### ISSUE THREAD

**Issue by calixphd** [lava-nc/lava-optimization#126]
Objective of issue: report integer overflow bug in OptimizationSolver. This must be solved to scale the SCIF model beyond 500 vars, and the NEBM beyond 1200 vars.

**I'm submitting a ...** 

- [x] bug report

**Steps to reproduce:**

- Run the following

```python
from lava.lib.optimization.problems.problems import QUBO
from lava.lib.optimization.solvers.generic.solver import OptimizationSolver, SolverConfig
from lava.lib.optimization.utils.generators.mis import MISProblem
import numpy as np

problem = MISProblem(num_vertices=500, connection_prob=0.95, seed=44).get_as_qubo(w_diag=4, w_off=32)
solver = OptimizationSolver(problem)

report = solver.solve(SolverConfig(
    backend="Loihi2", 
    target_cost=-2, 
    log_level=40,
    timeout=1000,
    hyperparameters={
        "neuron_model": "scif",
        "sustained_on_tau": 12,
        "noise_amplitude": 1,
        "noise_precision": 5
    })
)

print(f"Cost computed on CPU with numpy: {problem.evaluate_cost(report.best_state)}")
```

**Comment by calixphd** [comment]
This error was observed when the QUBO matrix is scaled with w_mult = 40. 
Host: LMT notified network reached target cost: -3087632
Host: LMT notified network reached target cost: -3087632
Host: stopping simulation at step: 4045

Basically any set of hyperparameters will return a false solution.

**Comment by phstratmann** [comment]
To add some info:
If the synaptic weights are high, then the solver integrates the cost, gets to a very high value, and shows an integer overflow. As a result, it assumes that it found a very good solution (-high number) and stops. Maybe integer overflow in the dendritic accumulator of the cost integrator?
