### ISSUE TITLE
Fixes for lava-optimization v0.1.1

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava-optimization#15]
Creating issue to resolve:

- Change solver interface to return solution values, removed default preconditioning in solver
- Fix typos in Tutorials
- More elaboration in the tutorials

**Comment by ashishrao7** [comment]
Taken care of in PR https://github.com/lava-nc/lava-optimization/pull/14

**Comment by mgkwill** [comment]
@ashishrao7 please link issues to PRs. Also if something is done please close the issue.
