### ISSUE TITLE
Delete debug variable from OptimizationSolver utiles

### ISSUE THREAD

**Issue by AlessandroPierro** [lava-nc/lava-optimization#153]
Objective of issue: remove debug variable

**Lava version:**
- [x] **0.2.3** (current version)

**I'm submitting a ...** 

- [x] bug report / cleanup

**Related code:**
- https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/builder.py#L184-L186
- https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/builder.py#L249-L250
- - https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/hierarchical_processes.py#L82
- https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/hierarchical_processes.py#L388
- https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/sub_process_models.py#L89
- https://github.com/lava-nc/lava-optimization/blob/1de5b0bc546ef11ab917659287bac8f8c1b44e9e/src/lava/lib/optimization/solvers/generic/sub_process_models.py#L89

**Comment by GaboFGuerra** [comment]
@AlessandroPierro, @srrisbud, @phstratmann Do we know who added this and for what reason?

**Comment by AlessandroPierro** [comment]
Resolved.
