### ISSUE TITLE
Remove solve() method to avoid duplication

### ISSUE THREAD

**Issue by AlessandroPierro** [lava-nc/lava-optimization#160]
Objective of issue: II would like to remove the solve() method to avoid duplication (and confusion), since it is just calling the homonymous member method from OptimizationSolver.

**Lava version:**
- [x] **0.3.0** (feature release)

**I'm submitting a ...** 

- [x] refactoring

**Comment by GaboFGuerra** [comment]
There's no duplication, it is offering the user the option of calling solve on a problem without explicitly creating a solver instance, this makes sense when the user is not interested on saving state but rather making a single call to solve. @mathisrichter Can you please weight on this?

**Comment by GaboFGuerra** [comment]
Also, this would not qualify as a bug. You are suggesting a refactoring of the API.
