### ISSUE TITLE
Mixed Integer Linear Programming

### ISSUE THREAD

**Issue by mhechthz** [lava-nc/lava-optimization#179]
Is there any planning on implementing a Mixed Integer Linear Programming Solver to Lava? QP is too restricted and most of our optimization problems are MILP type.

**Comment by mathisrichter** [comment]
The feature is not yet available in lava-optimization. But we are planning on developing it. There is already an issue for supporting MILP.
https://github.com/lava-nc/lava-optimization/issues/167

I am closing this issue as a duplicate.

**Comment by GaboFGuerra** [comment]
> Is there any planning on implementing a Mixed Integer Linear Programming Solver to Lava? QP is too restricted and most of our optimization problems are MILP type.

@mhechthz would you be able to share a bit more about the use cases you have in mind? Scale, variable ranges, constraint types, etc.?

**Comment by sharabhshukla** [comment]
an MILP would address a large number of problems in transportation routing, and also scheduling primarily in energy domain.

The generic structure remains very similar to an ILP, expect the variables is decomposed into two groups, one group of variables that can take on continuous values and few other variables are imposed with additional constraints that they can only take on binary values or discrete values between a min and max value.
