### ISSUE TITLE
[QUBO] Warn users that current CPU backend not up to date with Loihi implementation

### ISSUE THREAD

**Issue by phstratmann** [lava-nc/lava-optimization#249]
### User story
As a user, I want to be informed that the CPU backend shows substantially lower performance than the Loihi 2 backend.

**Comment by tim-shea** [comment]
Deprecate normally means to mark something that will be removed in a future version or is not actively maintained. I don't see how that applies here.

**Comment by phstratmann** [comment]
> Deprecate normally means to mark something that will be removed in a future version or is not actively maintained. I don't see how that applies here.

Adjusted, @tim-shea
