### ISSUE TITLE
Adding initial version of eventified Bayesian optimization system

### ISSUE THREAD

**Issue by shaymeister** [lava-nc/lava-optimization#30]
Objective of issue: Merging initial version of eventified Bayesian optimization system

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Expected behavior:**

- We need an initial optimization system that uses Bayesian Optimization to learn multi-dimensional black-box functions and find their global/local minima.
- The system shall have a similar architecture to the existing QP solver via models, processes, and a solver class.

**Comment by GaboFGuerra** [comment]
This was resolved by PR#32
