### ISSUE TITLE
Adding tutorial for initial eventified Bayesian optimization system.

### ISSUE THREAD

**Issue by shaymeister** [lava-nc/lava-optimization#31]
Objective of issue: Create a ipynb-based tutorial for the initial version of the eventified Bayesian optimization system.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [x] documentation request

**Expected behavior:**

- Lava-optimization should have have ipynb-based tutorial for the initial version of the eventified bayesian optimization system.

**Comment by GaboFGuerra** [comment]
Hi @shaymeister, do you have any update on this issue or plan to work on it or should we take it over?

**Comment by GaboFGuerra** [comment]
@shaymeister, I see this was already solved by your PR#32 :)
