### ISSUE TITLE
ProcessBuilder: Generic module to build processes within code

### ISSUE THREAD

**Issue by phstratmann** [lava-nc/lava-optimization#42]
Objective of issue: In the repo, Processes are produced on the fly in the SolverProcessBuilder. 
That's a feature which should not be hidden in the optimization library, but should be a generic tool in Lava.
In addition, in builder.py, the decorators are currently replaced in this way: 
`        setattr(solver_model, "implements_process", self.solver_process)
        # Get requirements of parent class
        super_res = solver_model.required_resources.copy()
        # Set new requirements not overwriting parent class requirements.
        setattr(solver_model, "required_resources", super_res + requirements)
        setattr(solver_model, "implements_protocol", protocol)`

That will work with the current decorators; but future pushes to the decorators may break it.

**Lava version:**
- [x] **0.3.0** (feature release)

**Comment by GaboFGuerra** [comment]
@phstratmann should this rater be split in a lava issue and a lava-optimization issue?

**Comment by mathisrichter** [comment]
This issue covers two points:
1. A feature request for something that can generate Lava Processes on the fly. This should be filed in the lava-nc/lava repository.
2. An idea to make the lava-optimization code more future-proof, which would be a feature request to be filed in lava-nc/lava-optimization.
@phstratmann Could you please change the stories accordingly?

**Comment by phstratmann** [comment]
Replaced by issues [#169](https://github.com/lava-nc/lava-optimization/issues/169) and [#580](https://github.com/lava-nc/lava/issues/580)
